name: console
description: lib for interactive console apps using dart.io and vt100
version: 0.0.1
homepage: https://github.com/erf/console

environment:
  sdk: ^3.6.0

dev_dependencies:
  lints: ^5.1.1
  test: ^1.16.0
