name: termio
description: minimal lib for interactive console apps
version: 0.1.0
homepage: https://github.com/erf/termio

environment:
  sdk: ^3.10.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.28.0
