name: termio
description: A minimal library for building interactive terminal applications with VT100 escape codes support.
version: 0.1.0
repository: https://github.com/erf/termio
issue_tracker: https://github.com/erf/termio/issues
topics:
  - terminal
  - console
  - cli
  - vt100
  - ansi

environment:
  sdk: ^3.10.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.28.0
